kookmin-sw/capstone-2020-6

web-frontend/src/components/JInput.css, web-frontend/src/components/JInput.tsx, web-frontend/src/pages/PageLogin.css, web-frontend/src/pages/PageLogin.tsx, web-frontend/src/stores/index.ts, web-frontend/src/stores/loginStore.ts
=> Web front login

web-frontend/src/components/CardProject.css, web-frontend/src/components/CardProject.tsx, web-frontend/src/components/MyPageCard.css, web-frontend/src/components/MypageCard.tsx, web-frontend/src/pages/PageMain.tsx, web-frontend/src/pages/PageMyPage.css, web-frontend/src/pages/PageMypage.tsx, web-frontend/src/stores/MyPageListStore.ts, web-frontend/src/stores/index.ts
- mypage card 만듦.
- careproject css 수정
- list map할 때, key 에러 수정
- mypage 페이지 임시 제작..
=> Web frontend mypage card

web-frontend/src/components/Popup.css, web-frontend/src/components/Popup.tsx, web-frontend/src/pages/PageMypage.tsx
- 팝업창 컴포넌트 개발
- 마이페이지에 테스트 코드 추가
=> Create popup component

web-frontend/src/Router.tsx, web-frontend/src/pages/PageMypagePW.css, web-frontend/src/pages/PageMypagePW.tsx
-  마이페이지 비밀번호 변경 페이지 추가
- 이 페이지는 의뢰자. 라벨링 참여자 모두 공용이므로 추가로 제작할 필요없음
=> Create mypage chage pw

web-frontend/src/Router.tsx, web-frontend/src/pages/PageLabelingRegister.css, web-frontend/src/pages/PageLabelingRegister.tsx
- 라벨링 등록 페이지 생성
- 등록 기간 드롭다운으로 구현 예정
- 파일 업로드 기능 구현 예정
=> 라벨링 등록 페이지 생성

web-frontend/src/pages/PageLabelingRegister.tsx
- 라디오버튼 기능 작동 구현
- 기한 설정 부분 드롭다운 추가
=> refactor: Handle radios and add dropdown

web-frontend/src/Router.tsx, web-frontend/src/pages/PageLabeling.tsx, web-frontend/src/pages/PageLabelingResult.tsx, web-frontend/src/pages/PageLabelingTextWrite.tsx, web-frontend/src/pages/PagePoints.tsx
라벨링(텍스트 단답형) 페이지 : PageTextLabelingWrite.tsx
라벨링 설명 페이지 : PageLabeling.tsx
마이 페이지 - 라벨링 결과 페이지 : PageLabelingResult
마이 페이지 - 포인트 관리 페이지 : PagePoints
Make Pages.tsx Pages.css and make link in Router
=> Web frontend making pages

web-frontend/package-lock.json, web-frontend/src/components/TsDropDown.tsx, web-frontend/src/pages/PageAbout.tsx, web-frontend/src/pages/PageLabelingRegister.tsx
- 라벨링 등록 페이지 UI 구현
- 소개 페이지 추후 멤버 사진 추가할 예정
=> 라벨링 등록 페이지와 소개 페이지 

src/web-frontend/package-lock.json, src/web-frontend/package.json, src/web-frontend/src/components/TsTag.tsx, src/web-frontend/src/pages/PageLabelingRegister.tsx
=> 라벨링 등록 페이지 키워드 추가

src/web-frontend/src/components/CardProject.tsx, src/web-frontend/src/pages/PageMain.tsx, src/web-frontend/src/pages/PageMypagePW.tsx, src/web-frontend/src/pages/PageMypageProject.css, src/web-frontend/src/pages/PageMypageProject.tsx, src/web-frontend/src/stores/MyPageProjectStore.ts, src/web-frontend/src/stores/index.ts
- mypage project store 생성
- 마이페이지 프로젝트관리 부분 카드 배치
- 카드에서 삭제, 수정 아이콘 추가
=> [의뢰자] mypage 프로젝트관리 

src/web-frontend/src/Router.tsx, src/web-frontend/src/pages/PageCaptcha.tsx
1. path '/captcha' 로 캡챠 페이지 접속 가능
2. Modal 을 통해 구현(Modal 은 컴포넌트화 시키지 않음)
3. 현재 Image Select 형식 그대로 가져와서 구현(Store 등 재구현 필요)
4. 제출 기능 구현 안됨
=> feat: Implement CAPTCHA v0

src/web-frontend/src/components/Navigation.css
- 프로젝트 등록 화면 dropdown 이 네비게이션 위에 보이는 문제 해결
- 네비게이션 바 z-index 값 조정
=> fix: Fix z-index error in navbar

src/web-frontend/package-lock.json, src/web-frontend/package.json, src/web-frontend/src/components/FileUpload.css, src/web-frontend/src/components/FileUpload.tsx, src/web-frontend/src/pages/PageLabelingRegister.tsx
=> Web frontend fileupload

src/web-frontend/src/components/FileUpload.tsx, src/web-frontend/src/pages/PageLabelingRegister.tsx
- 파일 업로드 썸네일 이미지 추가
- 파일 업로드 시, 해당 파일 확장자명과 일치하지 않으면 경고창 출현(?)
=> Web frontend register subject

src/web-frontend/src/components/CardProject.tsx, src/web-frontend/src/pages/PageMypageProject.tsx
=> 마이페이지 프로젝트 관리 디자인 수정

src/web-frontend/src/Router.tsx, src/web-frontend/src/pages/PageLabelingUpdateRegister.tsx, src/web-frontend/src/pages/PageMypageProject.tsx
- 프로젝트 명 누르면 수정 페이지로 이동
- 수정 페이지 생성
- 수정 페이지 관련 업데이트 스토어 만들어야함
=> 의뢰자 프로젝트 관리 페이지 수정

src/web-frontend/src/components/ProjectListTable.tsx, src/web-frontend/src/pages/PageViewAllProjects.tsx
- Project List Table 을 Component 화 시킴
- 근데 Table Cell 에 Link 같은 것을 추가해야하는 등의 제약 조건이 있음
- 최적화된 코드인지는 잘 모르겠음
=> feat: Project List Component V1

src/web-frontend/src/components/Loading.tsx
=> Implement loading components

src/web-frontend/src/pages/PageRegister.tsx
- 회원가입 화면에서 인증번호 전송 버튼, 인증번호 입력 창 삭제
=> refactor: Delete useless UI in register

src/web-backend/tsan_server/backend/schema/Project.py
=> getSubjectRequest 함수 구현

src/web-frontend/src/pages/PageMypageProject.tsx
- table component로 변경
- 수정 아이콘 추가
- 리다이렉션 수정
=> refactor: Use table component

src/web-frontend/src/components/CardProject.tsx, src/web-frontend/src/components/ProgressBar.css, src/web-frontend/src/pages/PageLabeling.tsx, src/web-frontend/src/stores/ProjectListStore.ts
- 프로그레스바 수정
- 메인 페이지 fullname 없을 때 예외처리(null말고)
- labeling description 글자 깨짐 수정
- 메인 페이지 라벨링 기간 보이도록 수정
=> Web frontend labeling

src/web-frontend/src/pages/PageLabelingImageCapture.css, src/web-frontend/src/pages/PageLabelingImageCapture.tsx
=> Web frontend imagecapture

src/web-backend/tsan_server/backend/schema/Project.py
state가 'END'인 주제 중 subject를 키워드로 찾기
=> getSubjectEndRequest 함수 구현

src/web-backend/tsan_server/backend/schema/Project.py
=> createRequest 수정 및 오류 발생

src/web-frontend/src/Router.tsx, src/web-frontend/src/pages/PageMain.tsx, src/web-frontend/src/pages/PageViewAllProjectsFinished.css, src/web-frontend/src/pages/PageViewAllProjectsFinished.tsx, src/web-frontend/src/stores/MyPageProjectStore.ts, src/web-frontend/src/stores/ProjectListStore.ts
- 완료된 프로젝트 더보기 버튼 및 페이지 구현
- 진행 중인 프로젝트 불러오기, 완료된 프로젝트 불러오기 쿼리 따로 구현 필요
- 완료된 프로젝트 검색 구현 필요
=> Web frontend view done projects

src/web-backend/tsan_server/backend/schema/Project.py
=> deleteRequest  함수 추가

src/web-frontend/src/Router.tsx, src/web-frontend/src/pages/PageLabeling.tsx, src/web-frontend/src/stores/LabelingPageStore.ts
labeling type 에 따른 url 을 string 에서 id 로 수정
=> feat: Modify labelingType url

src/web-frontend/src/pages/PageLabeling.tsx, src/web-frontend/src/pages/PageLabelingRegister.tsx, src/web-frontend/src/pages/PageMain.tsx, src/web-frontend/src/pages/PageMypageProject.tsx, src/web-frontend/src/pages/PageViewAllProjects.tsx, src/web-frontend/src/pages/PageViewAllProjectsFinished.tsx, src/web-frontend/src/stores/LabelingPageStore.ts, src/web-frontend/src/stores/ProjectListStore.ts
브랜치가 좀 잘못되었긴 하지만..
- Main page 에서 진행중인 프로젝트, 완료된 프로젝트 4개씩 보여줌
- 더보기 버튼으로 전체보기에 들어갔을 경우에는 모든 프로젝트 다 보여줌
=> Web frontend Main page

src/web-frontend/src/components/CardProject.tsx, src/web-frontend/src/components/ProgressBar.tsx
- 프로그레스바 수정
- 메인 페이지에서 완료된 프로젝트 종료 날짜 수정
=> Web frontend progress bar

src/web-frontend/src/pages/PageMypageProject.tsx, src/web-frontend/src/stores/MyPageProjectStore.ts
- getMyRequest API 연동
- 레이블링 참여자와 의뢰자 케이스로 구분
=> Web frontend mypage client

src/web-backend/tsan_server/backend/schema/Project.py, src/web-backend/tsan_server/tsan_server/schema.py
=> IncCurrentCycle 함수 구현

src/web-frontend/src/pages/PageLabelingResult.css, src/web-frontend/src/pages/PageLabelingResult.tsx, src/web-frontend/src/pages/PageMypageProject.tsx, src/web-frontend/src/stores/LabelingResultStore.ts, src/web-frontend/src/stores/MyPageProjectStore.ts
의뢰자만 볼 수 있는 결과 페이지에서 프로젝트 시작, 종료, 보상 기능 구현
근데 requester2 계정 말고 다른 계정일 때 보이지 않아서 테스트 해보아야할 것 같음
@jtjisgod
=> feat: Add project status manage buttons

src/web-frontend/src/components/DateTime.tsx, src/web-frontend/src/components/Time.tsx, src/web-frontend/src/pages/PagePoints.tsx
Point Page 에서 table 에 시간 찍히는 포맷 수정
2020-01-01T01:01:01
=> feat: Implement time component
